Repository b4mad/racing, pull requests merged in 2022-11, with the labels that each got.

#70 oschersleben
  pitcrew/Ferrari 488 GT3 Evo 2020-oschersleben gp.csv
Labels: size/XS

#72 shuffle secrets
  manifests/README.md
  manifests/grafana/base/grafana.yaml
  manifests/grafana/overlays/smaug/datasource.yaml
  manifests/grafana/overlays/smaug/kustomization.yaml
  manifests/grafana/overlays/smaug/secret-generator.yaml
  manifests/grafana/overlays/smaug/secret.enc.yaml
  manifests/influxdb/overlays/smaug/influxdb2-auth.enc.yaml
  manifests/influxdb/overlays/smaug/influxdb2-backup.enc.yaml
  manifests/influxdb/overlays/smaug/secret-generator.yaml
  manifests/influxdb2-values.yaml
  manifests/routes.yaml
  manifests/telegraf/base/deployment.yaml
  manifests/telegraf/overlays/smaug/sops_vault.enc.yaml
  manifests/telegraf/overlays/smaug/telegraf.conf
Labels: size/L, lgtm

#73 change to pgo
  manifests/kustomization.yaml
  manifests/postgresql/base/kustomization.yaml
  manifests/postgresql/base/pgbouncer.yaml
  manifests/postgresql/base/postgresql.yaml
  manifests/postgresql/base/postgresql_metrics_exporter.yaml
  manifests/postgresql/base/service_account.yaml
  manifests/postgresql/base/service_monitor.yaml
  manifests/postgresql/cluster.yaml
  manifests/postgresql/kustomization.yaml
  manifests/postgresql/overlays/smaug/kustomization.yaml
  manifests/postgresql/overlays/smaug/pgbouncer.ini
  manifests/postgresql/overlays/smaug/secret-generator.yaml
  manifests/postgresql/overlays/smaug/sops_vault.enc.yaml
Labels: size/XL

#74 psql experiment notebooks
  README.md
  manifests/postgresql/cluster.yaml
  notebooks/exploratory_data_analysis.ipynb
  notebooks/populate_tracks_table.ipynb
  notebooks/psql-port-forward.sh
  notebooks/psql.ipynb
  notebooks/psql.sh
  notebooks/stream_to_db.ipynb
  overlays/exploratory_data_analysis/Pipfile
  overlays/exploratory_data_analysis/Pipfile.lock
Labels: size/XXL

#79 nodeport for psql
  manifests/postgresql/cluster.yaml
Labels: size/XS

#81 add pitcrew for tim a holmes
  manifests/pitcrew/kustomization.yaml
  manifests/pitcrew/tim-a-holmes.yaml
Labels: size/M

#82 dashify base path
  pitcrew/app.py
Labels: size/XS

#83 onboarding automation
  .github/ISSUE_TEMPLATE/1_request_pitcrew.yaml
  scripts/jsonnet/pitcrew.jsonnet
  scripts/pitcrew_new.sh
Labels: size/L

#86 fix path in onboarding script
  scripts/pitcrew_new.sh
Labels: size/XS

#88 add Dallara P217 LMP2-watkinsglen 2021 fullcourse
  pitcrew/Dallara P217 LMP2-watkinsglen 2021 fullcourse.csv
Labels: size/XS

#89 fast lap analysis notebook
  .pre-commit-config.yaml
  notebooks/analysis/influx_query_sample.ipynb
  notebooks/fast_lap_analysis.ipynb
  pitcrew/Ferrari 488 GT3 Evo 2020-sebring international.csv
Labels: size/XXL

#91 Update Dallara P217 LMP2-watkinsglen 2021 fullcourse.csv
  pitcrew/Dallara P217 LMP2-watkinsglen 2021 fullcourse.csv
Labels: lgtm, approved, size/XS, ok-to-test

#80 paddock
  .gitignore
  notebooks/psql.sh
  paddock/.aicoe-ci.yaml
  paddock/.thoth.yaml
  paddock/Dockerfile
  paddock/Pipfile
  paddock/Pipfile.lock
  paddock/manage.py
  paddock/paddock/__init__.py
  paddock/paddock/asgi.py
  paddock/paddock/celery.py
  paddock/paddock/settings.py
  paddock/paddock/urls.py
  paddock/paddock/wsgi.py
  paddock/stewards/__init__.py
  paddock/stewards/admin.py
  paddock/stewards/apps.py
  paddock/stewards/migrations/__init__.py
  paddock/stewards/models.py
  paddock/stewards/tests.py
  paddock/stewards/urls.py
  paddock/stewards/views.py
  paddock/telemetry/__init__.py
  paddock/telemetry/admin.py
  paddock/telemetry/apps.py
  paddock/telemetry/influx.py
  paddock/telemetry/management/__init__.py
  paddock/telemetry/management/commands/__init__.py
  paddock/telemetry/management/commands/_private.py
  paddock/telemetry/management/commands/analyze.py
  paddock/telemetry/migrations/__init__.py
  paddock/telemetry/models.py
  paddock/telemetry/tasks.py
  paddock/telemetry/tests.py
  paddock/telemetry/views.py
Labels: lgtm, approved, size/XL

#94 :arrow_up: add paddock user, incr resource a little
  .aicoe-ci.yaml
  manifests/paddock/base/deployment_config.yaml
  manifests/postgresql/cluster.yaml
  paddock/.aicoe-ci.yaml
  paddock/Containerfile
  paddock/paddock/settings.py
Labels: size/L

#96 Updating the watkins glen file
  pitcrew/Dallara P217 LMP2-watkinsglen 2021 fullcourse.csv
Labels: approved, size/S, ok-to-test

#100 12factor django
  components/paddock/.env.example
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/settings.py
  manifests/paddock/base/deployment_config.yaml
Labels: size/L, approved

#101 paddock secrets n stuff
  manifests/paddock/base/deployment_config.yaml
  manifests/paddock/overlays/smaug/kustomization.yaml
  manifests/paddock/overlays/smaug/paddock-settings.enc.yaml
  manifests/paddock/overlays/smaug/secret-generator.yaml
Labels: size/L

#102 uwsgi serving
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/settings.py
  manifests/paddock/overlays/smaug/image_stream_tag.yaml
Labels: size/S

#105 WIP move pitcrew to aicoe-ci
  .aicoe-ci.yaml
  components/pitcrew/Dallara P217 LMP2-watkinsglen 2021 fullcourse.csv
  components/pitcrew/Ferrari 488 GT3 Evo 2020-monza full.csv
  components/pitcrew/Ferrari 488 GT3 Evo 2020-okayama full.csv
  components/pitcrew/Ferrari 488 GT3 Evo 2020-oschersleben gp.csv
  components/pitcrew/Ferrari 488 GT3 Evo 2020-sebring international.csv
  components/pitcrew/Ferrari 488 GT3 Evo 2020-summit summit raceway.csv
  components/pitcrew/Pipfile
  components/pitcrew/Pipfile.lock
  components/pitcrew/app.py
  components/pitcrew/coach.py
  components/pitcrew/history.py
  components/pitcrew/mqtt.py
  components/pitcrew/pyproject.toml
  components/pitcrew/validate_csv.py
  pitcrew/.aicoe-ci.yaml
  pitcrew/.thoth.yaml
  pitcrew/Dockerfile
Labels: size/M, do-not-merge/work-in-progress

#110 fast laps
  components/paddock/.env.example
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/management/commands/pitcrew.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/history.py
  manifests/paddock/base/deployment_config.yaml
  manifests/paddock/overlays/smaug/paddock-settings.enc.yaml
Labels: size/M

#111 sqlex
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/settings.py
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
  manifests/paddock/overlays/smaug/image_stream_tag.yaml
  manifests/paddock/overlays/smaug/paddock-settings.enc.yaml
Labels: size/M

#112 plotly app
  components/paddock/.gitignore
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/assets/logo-main-black.png
  components/paddock/paddock/pitcrew_app.py
  components/paddock/paddock/settings.py
  components/paddock/paddock/templates/base.html
  components/paddock/paddock/templates/pitcrew.html
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
  components/paddock/stewards/urls.py
  components/paddock/stewards/views.py
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/migrations/0002_auto_20221128_1323.py
  components/paddock/telemetry/migrations/0003_auto_20221128_1328.py
  components/paddock/telemetry/migrations/0004_auto_20221128_1411.py
  components/paddock/telemetry/migrations/0005_auto_20221128_1413.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/mqtt.py
  components/paddock/telemetry/views.py
  notebooks/analysis/influx_query_sample.ipynb
  notebooks/fast_lap_analysis.pdf
  sample-small.json
  sample.json
Labels: size/XXL

#114 v2 telegraf
  manifests/telegraf/overlays/smaug/telegraf.conf
Labels: size/M

#116 coaches and sessions
  components/paddock/.env.example
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/settings.py
  components/paddock/paddock/templates/pitcrew_index.html
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
  components/paddock/telemetry/migrations/0006_alter_coach_error.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/mqtt.py
  manifests/pitcrew/kustomization.yaml
Labels: size/L

#115 pitcrew index page
  components/paddock/paddock/templates/pitcrew_index.html
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/mqtt.py
Labels: size/M

#113 add notebooks overlay
  .thoth.yaml
Labels: kind/feature, approved, size/XS

#119 docs screenshot
  docs/cc_folder.png
  docs/cc_log.png
  docs/cc_mqtt_coach.png
  docs/cc_settings_mqtt.png
  docs/cc_settings_tts.png
Labels: size/XS

#121 readme
  .gitignore
  README.md
  components/paddock/paddock/settings.py
  components/paddock/paddock/templates/base.html
  components/paddock/paddock/templates/fastlap.html
  components/paddock/paddock/templates/home.html
  components/paddock/paddock/templates/pitcrew_index.html
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
  components/paddock/telemetry/management/commands/pitcrew.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/pitcrew/Ferrari 488 GT3 Evo 2020-oschersleben gp.csv
  dashboards/operate-first/influxdb-2-0-oss-metrics_rev4.json
  dashboards/operate-first/influxdb.json
  docs/mqtt_telemetry.json
  flux/tasks/brake_start.flux
  flux/tasks/brake_start.py
  flux/tasks/gears.flux
  flux/tasks/gears.py
  notebooks/AI_Coaching.pdf
  notebooks/fast_lap_analysis2.ipynb
  scripts/publish.sh
  scripts/subscribe.sh
Labels: size/XXL
