Repository b4mad/racing, pull requests merged in 2022-10, with the labels that each got.

#42 mosquitto update
  README.md
  manifests/mosquitto/deployment.yaml
  manifests/mosquitto/dynamic-security.json
  manifests/mosquitto/kustomization.yaml
  manifests/mosquitto/mosquitto.conf
  manifests/mosquitto/mosquitto.conf.old
  manifests/mosquitto/passwd
  manifests/mosquitto/secret-generator.yaml
  manifests/mosquitto/sops_vault.enc.yaml
Labels: size/XL

#48 disable dynamic security in mosquitto
  manifests/mosquitto/mosquitto.conf
  manifests/mosquitto/services.yaml
Labels: size/M, approved

#53 coach
  coach/coach.py
  coach/racing.csv
Labels: size/L

#54 add telegraf metrics service
  manifests/telegraf/base/kustomization.yaml
Labels: approved, size/XS

#56 fix secret-generator names
  manifests/postgresql/overlays/smaug/secret-generator.yaml
  manifests/telegraf/overlays/smaug/secret-generator.yaml
Labels: approved, size/XS

#60 refine resource to be used by deployments
  manifests/keycloak/base/deployment_config.yaml
  manifests/postgresql/base/pgbouncer.yaml
Labels: approved, size/S, hacktoberfest-accepted

#61 coach
  .pre-commit-config.yaml
  coach/Pipfile.lock
  coach/coach.py
  pitcrew/.thoth.yaml
  pitcrew/Ferrari 488 GT3 Evo 2020-monza full.csv
  pitcrew/Ferrari 488 GT3 Evo 2020-okayama full.csv
  pitcrew/Ferrari 488 GT3 Evo 2020-summit summit raceway.csv
  pitcrew/Pipfile
  pitcrew/Pipfile.lock
  pitcrew/app.py
  pitcrew/coach.py
  pitcrew/history.py
  pitcrew/mqtt.py
Labels: size/XXL

#59 refactored secrets to ENV
  ai/Pipfile
  ai/analysis/.env.sample
  ai/analysis/Pipfile
  ai/analysis/Pipfile.lock
  ai/analysis/README.md
  ai/analysis/requirements.txt
  ai/analysis/src/compare.py
  ai/analysis/src/demo.ipynb
  ai/analysis/src/eda-influx.ipynb
  ai/analysis/src/influx_query_sample.ipynb
  ai/analysis/src/preprocess.py
  ai/analysis/src/suggestions.png
Labels: size/XXL, approved, hacktoberfest-accepted

#63 sanity checking
  pitcrew/Pipfile
  pitcrew/Pipfile.lock
  pitcrew/coach.py
  pitcrew/history.py
Labels: size/M

#65 dash
  pitcrew/app.py
Labels: size/L

#66 change tag to latest
  .pre-commit-config.yaml
  manifests/pitcrew/durandom.yaml
Labels: size/XS

#68 dash
  pitcrew/app.py
Labels: size/M
