Repository b4mad/racing, pull requests merged in 2022-09, with the labels that each got.

#18 telegraf: renamed and reconfigured to use TOML
  manifests/telegraf/kustomization.yaml
  manifests/telegraf/telegraf.toml
Labels: size/M, lgtm, approved

#34 adjust topic for crewchief
  manifests/telegraf/telegraf.toml
Labels: size/XS

#36 main
  manifests/grafana/dashboards/details-crew-chief.yaml
  manifests/grafana/dashboards/details.yaml
  manifests/grafana/dashboards/overview.yaml
Labels: size/XS

#38 update readme
  README.md
  coach/Pipfile
  coach/Pipfile.lock
  coach/coach.py
  docs/architecture.png
Labels: size/L

#37 coach POC
  README.md
  coach/Pipfile
  coach/Pipfile.lock
  coach/coach.py
  docs/architecture.png
Labels: size/L

#39 updated mosquitto and telegraf manifests
  manifests/mosquitto/deployment.yaml
  manifests/mosquitto/kustomization.yaml
  manifests/mosquitto/mosquitto.conf
  manifests/mosquitto/mosquitto.conf.old
  manifests/mosquitto/passwd
  manifests/mosquitto/service_account.yaml
  manifests/mosquitto/services.yaml
  manifests/telegraf/deployment.yaml
  manifests/telegraf/kustomization.yaml
  manifests/telegraf/service.yaml
  manifests/telegraf/service_account.yaml
  manifests/telegraf/telegraf.conf
Labels: size/XXL

#40 fix commonLabels
  manifests/kustomization.yaml
Labels: size/XS

#43 Grafana Dashboards
  manifests/grafana/dashboards/details-crew-chief.json
  manifests/grafana/dashboards/details-crew-chief.yaml
  manifests/grafana/dashboards/kustomization.yaml
  manifests/grafana/dashboards/landingpage.json
  manifests/grafana/grafana.yaml
Labels: size/XXL
