Repository b4mad/racing, pull requests merged in 2022-05, with the labels that each got.

#14 feature/metrics and backup enabled
  .gitignore
  manifests/.sops.yaml
  manifests/README.md
  manifests/b4mad-racing-influxdb-backup.enc.yaml
  manifests/influxdb2-values.yaml
  manifests/kustomization.yaml
  manifests/routes.yaml
  manifests/secret-generator.yaml
  manifests/telegraf/deployment.yaml
  manifests/telegraf/service.yaml
  manifests/telemetry-route.yaml
Labels: size/L, lgtm, approved

#16 feature/service monitoring
  manifests/kustomization.yaml
  manifests/mosquitto/deployment.yaml
  manifests/mosquitto/service_monitor.yaml
  manifests/mosquitto/services.yaml
  manifests/secrets-b4mad-racing-influxdb-backup.yaml
  manifests/service_monitor.yaml
  manifests/telegraf/service_monitor.yaml
Labels: size/L

#19 udapte telgraf topic
  manifests/telegraf/telegraf.conf
Labels: approved, size/XS

#23 tweaks to the readme
  README.md
Labels: size/M, approved

#20 Updated Docker to current standard
  docker-compose/grafana/provisioning/datasources/influxdb.yml
  docker-compose/telegraf/telegraf.conf
Labels: size/M, approved
