Repository b4mad/racing, pull requests merged in 2022-12, with the labels that each got.

#122 redo db
  components/paddock/paddock/views.py
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/migrations/0001_initial.py
  components/paddock/telemetry/migrations/0002_auto_20221128_1323.py
  components/paddock/telemetry/migrations/0002_auto_20221201_1729.py
  components/paddock/telemetry/migrations/0003_auto_20221128_1328.py
  components/paddock/telemetry/migrations/0004_auto_20221128_1411.py
  components/paddock/telemetry/migrations/0005_auto_20221128_1413.py
  components/paddock/telemetry/migrations/0006_alter_coach_error.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/crew.py
  manifests/telegraf/overlays/smaug/telegraf.conf
Labels: size/L

#123 quick fix
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/pitcrew/crew.py
Labels: size/XS

#124 Telemetry n fastest laps
  notebooks/fast_lap_analysis.ipynb
Labels: size/XXL, needs-ok-to-test

#126 currentlaptime
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/management/commands/analyze.py
  docs/mqtt_telemetry.json
Labels: size/M

#125 fix typo
  README.md
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
Labels: kind/bug, size/L, kind/documentation

#127 main
  manifests/grafana/overlays/smaug/dashboards/details-crew-chief.json
  manifests/grafana/overlays/smaug/dashboards/landingpage.json
  manifests/grafana/overlays/smaug/dashboards/user.json
Labels: size/XS

#129 fix lap time recording
  components/paddock/paddock/settings.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/pitcrew/crew.py
  notebooks/fast_lap_analysis-test.ipynb
  notebooks/fast_lap_analysis-v1.ipynb
  notebooks/fast_lap_analysis-v2.ipynb
  notebooks/inspect_lap.ipynb
Labels: size/XXL

#130 telegraf time
  manifests/telegraf/overlays/smaug/telegraf.conf
Labels: size/XL

#131 automated fast lap analysis
  README.md
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/management/commands/pitcrew.py
  components/paddock/telemetry/migrations/0003_fastlap_driver.py
  components/paddock/telemetry/migrations/0004_lap_valid.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/mqtt.py
  notebooks/inspect_lap.ipynb
Labels: size/XXL

#132 fix migrations
  components/paddock/telemetry/migrations/0003_auto_20221203_2100.py
  components/paddock/telemetry/migrations/0004_lap_valid.py
  components/paddock/telemetry/models.py
Labels: size/S

#133 quick fix timing
  components/paddock/telemetry/pitcrew/crew.py
Labels: size/S

#135 better lap checking in pitcrew
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/telemetry/management/commands/replay.py
  components/paddock/telemetry/migrations/0004_lap_end.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/crew.py
Labels: size/XL

#138 analyzer and coach
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/management/commands/pitcrew.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/history.py
Labels: size/L

#144 fix lap saving
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/history.py
Labels: size/S

#147 lap / session cleaning
  components/paddock/telemetry/pitcrew/crew.py
Labels: size/M

#148 less logging
  components/paddock/telemetry/pitcrew/history.py
Labels: size/M

#153 scope car to game
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/history.py
Labels: size/S

#155 increase the PCV size for influxdb2
  manifests/influxdb2-values.yaml
Labels: approved, size/XS

#157 Create average track points
  notebooks/track_sections_from_coordinates.ipynb
Labels: size/XXL, needs-ok-to-test
