Repository b4mad/racing, pull requests merged in 2022-04, with the labels that each got.

#5 add kustomize manifests for telegraf
  manifests/README.md
  manifests/kustomization.yaml
  manifests/telegraf/deployment.yaml
  manifests/telegraf/service.yaml
  manifests/telegraf/service_account.yaml
  manifests/telegraf/telegraf.conf
Labels: size/L

#6 add mosquitto
  manifests/kustomization.yaml
  manifests/mosquitto/deployment.yaml
  manifests/mosquitto/kustomization.yaml
  manifests/mosquitto/mosquitto.conf
  manifests/mosquitto/service_account.yaml
  manifests/mosquitto/services.yaml
  manifests/telegraf/deployment.yaml
  manifests/telegraf/kustomization.yaml
  manifests/telegraf/telegraf.conf
Labels: size/L

#8 remove some python code we dont need
  Pipfile
  Pipfile.lock
  README.md
  client_pub_opts.py
Labels: size/L

#7 client docs
  README.md
Labels: size/S

#9 add influxdb to the manifests
  manifests/README.md
  manifests/influxdb2-values.yaml
Labels: size/M

#10 grafana
  README.md
  manifests/grafana/dashboards/kustomization.yaml
  manifests/grafana/dashboards/landingpage-dashboard-configmap.yaml
  manifests/grafana/datasource.yaml
  manifests/grafana/grafana-datasource-serviceaccount.yaml
  manifests/grafana/grafana-route.yaml
  manifests/grafana/grafana.yaml
  manifests/grafana/kustomization.yaml
Labels: size/L

#12 bump manifests
  manifests/README.md
  manifests/grafana/dashboards/landingpage-dashboard-configmap.yaml
  manifests/grafana/datasource.yaml
  manifests/grafana/grafana.yaml
  manifests/influxdb2-values.yaml
  manifests/kustomization.yaml
  manifests/telegraf/deployment.yaml
  manifests/telegraf/kustomization.yaml
  manifests/telegraf/service.yaml
  manifests/telegraf/service_account.yaml
  manifests/telegraf/telegraf.conf
Labels: size/L

#13 main
  manifests/grafana/dashboards/landingpage-dashboard-configmap.yaml
  manifests/telegraf/telegraf.conf
Labels: size/L
