Repository b4mad/racing, pull requests merged in 2023-08, with the labels that each got.

#379 add car class
  components/paddock/scripts/dumpdata.sh
  components/paddock/telemetry/fixtures/car.json
  components/paddock/telemetry/fixtures/coach.json
  components/paddock/telemetry/fixtures/fastlap.json
  components/paddock/telemetry/fixtures/filter.sh
  components/paddock/telemetry/fixtures/track.json
  components/paddock/telemetry/migrations/0013_alter_coach_mode.py
  components/paddock/telemetry/migrations/0014_carclass_car_car_class.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/firehose.py
  components/paddock/telemetry/pitcrew/session.py
  components/paddock/telemetry/pitcrew/session_saver.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  components/paddock/telemetry/tests/data/session_1692140843_df.csv.gz
  components/paddock/telemetry/tests/test_session.py
Labels: size/L, approved

#383 test trigger file added
  .test-trigger
Labels: approved, size/XS

#384 test trigger file removed
  .test-trigger
Labels: approved, size/XS

#386 extract driver dashboard to json file
  manifests/base/grafana-v5/dashboards/driver.json
  manifests/base/grafana-v5/dashboards/driver.yaml
Labels: size/XXL

#387 extract dashboard to json file
  manifests/base/grafana-v5/dashboards/details-crew-chief.json
  manifests/base/grafana-v5/dashboards/details-crew-chief.yaml
  manifests/base/grafana-v5/dashboards/details-extended.json
  manifests/base/grafana-v5/dashboards/details-extended.yaml
  manifests/base/grafana-v5/dashboards/driver-extended.json
  manifests/base/grafana-v5/dashboards/driver-extended.yaml
  manifests/base/grafana-v5/dashboards/landingpage.json
  manifests/base/grafana-v5/dashboards/landingpage.yaml
  manifests/base/grafana-v5/dashboards/track-standings.json
  manifests/base/grafana-v5/dashboards/track-standings.yaml
Labels: size/XXL

#388 fix some uids and revert back to old landingpage
  manifests/base/grafana-v5/dashboards/driver-extended.json
  manifests/base/grafana-v5/dashboards/landingpage-extended.json
  manifests/base/grafana-v5/dashboards/landingpage-extended.yaml
  manifests/base/grafana-v5/dashboards/landingpage.json
Labels: size/XXL

#389 add dashboard extended
  manifests/base/grafana-v5/dashboards/kustomization.yaml
  manifests/base/grafana-v5/dashboards/landingpage-extended.json
Labels: size/XS

#390 reenable scatterplot
  manifests/base/grafana-v5/dashboards/details-crew-chief.yaml
Labels: size/XS

#391 fix uid in datasource
  manifests/base/grafana-v5/dashboards/details-crew-chief.json
  manifests/base/grafana-v5/dashboards/landingpage-extended.json
Labels: size/S

#392 tweak dashboard names
  manifests/base/grafana-v5/dashboards/details-extended.json
  manifests/base/grafana-v5/dashboards/landingpage-extended.json
  manifests/base/grafana-v5/dashboards/landingpage.json
Labels: size/XS

#393 resync period
  manifests/base/grafana-v5/dashboards/details-crew-chief.yaml
  manifests/base/grafana-v5/dashboards/landingpage-extended.yaml
  manifests/base/grafana-v5/dashboards/landingpage.yaml
Labels: size/XS

#395 fix session URL
  manifests/base/grafana-v5/dashboards/details-crew-chief.yaml
Labels: size/XS

#397 landmarks
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/management/commands/load_data.py
  components/paddock/telemetry/management/commands/load_devel_data.py
  components/paddock/telemetry/management/commands/trackLandmarksData.json
  components/paddock/telemetry/migrations/0015_landmark.py
  components/paddock/telemetry/migrations/0016_landmark_from_cc.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/firehose.py
Labels: size/XXL, approved

#398 fix no valid laps found
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
Labels: size/XS

#400 sm paddock metrics
  components/paddock/paddock/settings.py
  manifests/base/paddock/deployment_config.yaml
  manifests/env/nostromo-stage/kustomization.yaml
Labels: approved, size/S

#401 phobos.test and psql s3 backup
  manifests/base/mosquitto/README.md
  manifests/base/mosquitto/secret/kustomization.yaml
  manifests/base/mosquitto/secret/secret.yaml
  manifests/base/mosquitto/services.yaml
  manifests/base/paddock/paddock-settings/kustomization.yaml
  manifests/base/paddock/paddock-settings/paddock-settings.yaml
  manifests/base/postgresql/README.md
  manifests/base/postgresql/cluster.yaml
  manifests/base/postgresql/pgo-reader/README.md
  manifests/base/postgresql/pgo-reader/kustomization.yaml
  manifests/base/postgresql/pgo-reader/pgo-reader.yaml
  manifests/base/postgresql/pgo-s3-creds/kustomization.yaml
  manifests/base/postgresql/pgo-s3-creds/pgo-s3-creds.yaml
  manifests/env/phobos.test/kustomization.yaml
  manifests/env/phobos.test/mosquitto/kustomization.yaml
  manifests/env/phobos.test/paddock/kustomization.yaml
  manifests/env/phobos.test/postgresql/kustomization.yaml
  manifests/env/phobos.test/postgresql/restore.yaml
  manifests/env/phobos/paddock-settings.sops.yaml
  manifests/env/phobos/postgresql/kustomization.yaml
  manifests/env/phobos/postgresql/pgo-reader.sops.yaml
  manifests/env/phobos/postgresql/pgo-s3-creds.sops.yaml
Labels: size/L, approved

#403 fix user workload monitoring
  manifests/env/nostromo-stage/namespace.yaml
  manifests/env/phobos.dev/namespace.yaml
  manifests/env/phobos.test/namespace.yaml
  manifests/env/phobos/namespace.yaml
Labels: approved, size/S

#406 adjust psql settings... again
  manifests/base/postgresql/README.md
  manifests/base/postgresql/cluster.yaml
  manifests/base/postgresql/pgo-s3-creds/pgo-s3-creds.yaml
  manifests/env/phobos/postgresql/kustomization.yaml
  manifests/env/phobos/postgresql/pgo-s3-creds.sealed.yaml
  manifests/env/phobos/postgresql/pgo-s3-creds.sops.yaml
Labels: size/S

#407 add missing s3 pgbackrest settings
  manifests/env/phobos/postgresql/pgo-s3-creds.sealed.yaml
  manifests/env/phobos/postgresql/pgo-s3-creds.sops.yaml
Labels: size/XS

#408 fine tune track guide
  components/paddock/telemetry/fixtures/trackguide.json
  components/paddock/telemetry/fixtures/trackguidenote.json
  components/paddock/telemetry/management/commands/track_guide.csv
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/tests/data/responses_test_track_guide.txt
Labels: size/L

#409 track guide mazda
  components/paddock/scripts/dumpdata.sh
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/fixtures/car.json
  components/paddock/telemetry/fixtures/fastlapsegment.json
  components/paddock/telemetry/fixtures/filter.sh
  components/paddock/telemetry/fixtures/landmark.json
  components/paddock/telemetry/fixtures/lap.json
  components/paddock/telemetry/fixtures/session.json
  components/paddock/telemetry/fixtures/track.json
  components/paddock/telemetry/fixtures/trackguide.json
  components/paddock/telemetry/fixtures/trackguidenote.json
  components/paddock/telemetry/management/commands/load_data.py
  components/paddock/telemetry/management/commands/track_guide.csv
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
  components/paddock/telemetry/tests/data/session_1690362827_df.csv.gz
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/telemetry/tests/test_racing_stats.py
  components/paddock/track_guides/Automobilista 2--BMW M4 GT4--Monza:Monza_2020.csv
  components/paddock/track_guides/iRacing--BMW M4 GT4--monza full.csv
  components/paddock/track_guides/iRacing--Mazda MX-5 Cup--okayama short.csv
Labels: size/XXL, approved

#410 track guide for mazda
  components/paddock/scripts/dumpdata.sh
  components/paddock/telemetry/fixtures/trackguide.json
  components/paddock/telemetry/fixtures/trackguidenote.json
  components/paddock/telemetry/management/commands/load_data.py
  components/paddock/telemetry/migrations/0018_trackguidenote_at_alter_coach_mode_alter_fastlap_car_and_more.py
  components/paddock/telemetry/migrations/0019_alter_trackguidenote_at.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/track_guides/iRacing--Mazda MX-5 Cup--okayama short.csv
Labels: approved

#411 ✨ updated pipelines-as-code
  .pre-commit-config.yaml
  .tekton/on-pullrequest.yaml
  .tekton/push.yaml
Labels: size/L, approved

#414 track guide for mazda - first corner
  components/paddock/telemetry/fixtures/trackguide.json
  components/paddock/telemetry/fixtures/trackguidenote.json
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_track_guide.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
  components/paddock/track_guides/iRacing--Mazda MX-5 Cup--okayama short.csv
Labels: size/L, approved

#415 more track guide details
  components/paddock/telemetry/fixtures/trackguide.json
  components/paddock/telemetry/fixtures/trackguidenote.json
  components/paddock/telemetry/management/commands/load_data.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
  components/paddock/track_guides/iRacing--Mazda MX-5 Cup--okayama short.csv
Labels: size/XXL, approved
