Repository b4mad/racing, pull requests merged in 2023-09, with the labels that each got.

#417 scoring trackg guide
  components/paddock/telemetry/fixtures/trackguide.json
  components/paddock/telemetry/fixtures/trackguidenote.json
  components/paddock/telemetry/migrations/0020_trackguidenote_score.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_track_guide.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
  components/paddock/track_guides/iRacing--Mazda MX-5 Cup--okayama short.csv
Labels: size/XXL, approved

#418 bugfix if at == segment.start
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
  components/paddock/track_guides/iRacing--Mazda MX-5 Cup--okayama short.csv
Labels: size/M, approved

#420 more fine tuning of the track guide handling
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
Labels: size/L, approved

#424 fix interpolation range
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
Labels: approved, size/S

#425 fix gear if gear is NaN
  components/paddock/telemetry/fast_lap_analyzer.py
Labels: approved, size/XS

#427 issue426
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/settings.py
  components/paddock/paddock/templates/base.html
  components/paddock/paddock/templates/home.html
  components/paddock/paddock/templates/social_account_login.html
  components/paddock/paddock/urls.py
  components/paddock/telemetry/templatetags/__init__.py
  components/paddock/telemetry/templatetags/login_extras.py
  manifests/base/paddock/deployment_config.yaml
  manifests/base/paddock/paddock-settings/paddock-settings.yaml
  manifests/env/nostromo-stage/secrets/paddock-socialaccounts.yaml
  manifests/env/phobos/kustomization.yaml
  manifests/env/phobos/secrets/paddock-settings.sealed.yaml
  manifests/env/phobos/secrets/paddock-settings.sops.yaml
  manifests/env/phobos/secrets/paddock-socialaccounts.yaml
  manifests/env/phobos/secrets/secret.sealed.yaml
Labels: size/XXL

#431 ✨ add a few application-lelvel key metrics
  components/paddock/kpi/__init__.py
  components/paddock/kpi/views.py
  components/paddock/paddock/metrics.py
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
Labels: size/S

#434 bump psql pvc
  manifests/env/phobos/postgresql/kustomization.yaml
Labels: size/XS

#428 track guide application
  components/paddock/notebooks/segments.ipynb
  components/paddock/telemetry/migrations/0022_alter_coach_mode.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/application/__init__.py
  components/paddock/telemetry/pitcrew/application/application.py
  components/paddock/telemetry/pitcrew/application/debug_application.py
  components/paddock/telemetry/pitcrew/application/response.py
  components/paddock/telemetry/pitcrew/application/session.py
  components/paddock/telemetry/pitcrew/application/track_guide_application.py
  components/paddock/telemetry/pitcrew/coach_app.py
  components/paddock/telemetry/pitcrew/coach_watcher.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/tests/data/responses_test_debug_app.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_iracing.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_no_data_found.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_no_trackguide.txt
  components/paddock/telemetry/tests/test_debug_app.py
  components/paddock/telemetry/tests/test_track_guide_app.py
  docs/coach.md
  docs/track guide.md
Labels: approved, size/XL

#438 better metrics
  .pre-commit-config.yaml
  components/paddock/.containerignore
  components/paddock/CHANGELOG.md
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/kpi/__init__.py
  components/paddock/kpi/views.py
  components/paddock/paddock/metrics.py
  components/paddock/paddock/metrics_exporter.py
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
  components/paddock/pyproject.toml
  manifests/base/paddock/metrics-exporter/deployment.yaml
  manifests/base/paddock/metrics-exporter/ingress.yaml
  manifests/base/paddock/metrics-exporter/kustomization.yaml
  manifests/base/paddock/metrics-exporter/monitoring_alerting.yaml
  manifests/base/paddock/metrics-exporter/service.yaml
  manifests/env/nostromo-stage/paddock/kustomization.yaml
  manifests/env/phobos/paddock/kustomization.yaml
Labels: size/L, approved

#439 feat: add alerting for pgsql diff backup cronjob execution and pvc usage
  manifests/env/nostromo-stage/postgresql/alerting.yaml
  manifests/env/nostromo-stage/postgresql/kustomization.yaml
  manifests/env/phobos/postgresql/alerting.yaml
  manifests/env/phobos/postgresql/kustomization.yaml
Labels: size/M, approved

#440 reenable paddock metrics
  components/paddock/CHANGELOG.md
  components/paddock/paddock/urls.py
  components/paddock/pyproject.toml
Labels: approved, size/S

#441 main
  components/Pipfile
  components/paddock/CHANGELOG.md
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/pyproject.toml
Labels: size/L, approved

#442 incr influx pvc size
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  manifests/env/phobos/influxdb/kustomization.yaml
Labels: size/L, approved

#444 fix interpolation range
  components/paddock/telemetry/analyzer.py
Labels: approved, size/XS

#445 test(paddock-tests): add a few k6-based test scripts
  .gitignore
  components/paddock/k6.d/README.md
  components/paddock/k6.d/average-load.js
  components/paddock/k6.d/browser.js
  components/paddock/k6.d/e2e.js
  components/paddock/k6.d/smoke.js
Labels: size/L, approved

#448 add sentry
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/settings.py
  manifests/env/phobos/secrets/paddock-settings.sealed.yaml
  manifests/env/phobos/secrets/paddock-settings.sops.yaml
Labels: size/L, approved

#450 include fast lap app
  components/paddock/paddock/views.py
Labels: approved, size/XS

#437 track guide app recon laps
  components/paddock/telemetry/fixtures/trackguide.json
  components/paddock/telemetry/fixtures/trackguidenote.json
  components/paddock/telemetry/migrations/0023_remove_trackguidenote_at_start_and_more.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/application/application.py
  components/paddock/telemetry/pitcrew/application/debug_application.py
  components/paddock/telemetry/pitcrew/application/response.py
  components/paddock/telemetry/pitcrew/application/track_guide_application.py
  components/paddock/telemetry/pitcrew/coach_app.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_debug_app.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_iracing.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_no_trackguide.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
  components/paddock/telemetry/tests/data/session_1694266648_df.csv.gz
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/telemetry/tests/test_debug_app.py
  components/paddock/telemetry/tests/test_track_guide_app.py
  components/paddock/track_guides/iRacing--Mazda MX-5 Cup--okayama short.csv
Labels: size/XXL, approved

#452 recon laps v2
  components/paddock/telemetry/pitcrew/application/track_guide_application.py
  components/paddock/telemetry/tests/test_track_guide_app.py
Labels: size/L, approved

#453 better wraps
  components/paddock/telemetry/pitcrew/coach_app.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/tests/data/responses_test_debug_app.txt
Labels: size/M, approved

#454 fix at
  components/paddock/telemetry/pitcrew/application/track_guide_application.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_iracing.txt
Labels: size/M, approved

#456 adjust sentry logging
  components/paddock/paddock/settings.py
Labels: approved, size/XS

#461 fix distance response
  components/paddock/telemetry/pitcrew/application/response.py
  components/paddock/telemetry/pitcrew/logging.py
  components/paddock/telemetry/pitcrew/mqtt.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_iracing.txt
  components/paddock/telemetry/tests/test_track_guide_app.py
Labels: size/L, approved

#462 rework responses
  components/paddock/paddock/settings.py
  components/paddock/telemetry/pitcrew/application/application.py
  components/paddock/telemetry/pitcrew/application/response.py
  components/paddock/telemetry/pitcrew/application/track_guide_application.py
  components/paddock/telemetry/tests/data/responses_test_debug_app.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_iracing.txt
Labels: size/L, approved

#464 trackguide app
  components/paddock/paddock/fastlap_app.py
  components/paddock/telemetry/fixtures/trackguide.json
  components/paddock/telemetry/fixtures/trackguidenote.json
  components/paddock/telemetry/migrations/0024_trackguidenote_mode_trackguidenote_sort_key.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/application/application.py
  components/paddock/telemetry/pitcrew/application/track_guide_application.py
  components/paddock/telemetry/pitcrew/coach_app.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_iracing.txt
  components/paddock/telemetry/tests/data/responses_test_track_guide_iracing.txt
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/telemetry/tests/test_track_guide_app.py
  components/paddock/track_guides/iRacing--Mazda MX-5 Cup--okayama short.csv
Labels: size/XXL, approved

#465 recon laps trackguide
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/telemetry/pitcrew/application/track_guide_application.py
  components/paddock/telemetry/pitcrew/coach_app.py
  components/paddock/telemetry/tests/data/responses_test_track_guide_app_iracing.txt
Labels: approved, size/XL

#467 fix 466
  components/paddock/telemetry/pitcrew/segment.py
Labels: approved, size/XS

#468 build: add sops2sealedsecret to dev packages
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
Labels: size/L, approved

#460 build: update mosquitto and telegraf to their latest version
  manifests/env/nostromo-stage/kustomization.yaml
Labels: approved, size/XS

#473 read version from pyproject toml
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/__init__.py
  components/paddock/pyproject.toml
  manifests/base/paddock/deployment_config.yaml
Labels: size/L, approved

#471 refactor(mosquitto): doing the last step of migrating to the new secret
  manifests/base/mosquitto/deployment.yaml
  manifests/base/telegraf/deployment.yaml
  manifests/env/nostromo-stage/mosquitto/kustomization.yaml
  manifests/env/phobos/mosquitto/kustomization.yaml
Labels: size/M, approved
