Repository b4mad/racing, pull requests merged in 2023-07, with the labels that each got.

#328 save driver sectors
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/test_coach.py
Labels: size/XXL, approved

#329 fix issue with too short lap dataframe
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/pitcrew/segment.py
Labels: size/XXL, approved

#330 add some defaults, so that argocd sync view is more in sync
  manifests/base/paddock/deployment_config.yaml
Labels: approved, size/S

#331 split laps at the start line
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/paddock/fastlap_app.py
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  components/paddock/telemetry/visualizer.py
  manifests/base/paddock/cronjobs/cronjob_analyze.yaml
Labels: size/XXL, approved

#333 some changes applied on prod, now in git
  manifests/env/phobos/postgresql/kustomization.yaml
Labels: approved, size/S

#337 adjust psql backups
  manifests/base/postgresql/cluster.yaml
  manifests/env/phobos/postgresql/kustomization.yaml
Labels: approved, size/XS

#338 store sector time / timestamp models
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/scripts/dumpdata.sh
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/fixtures/coach.json
  components/paddock/telemetry/fixtures/fastlap.json
  components/paddock/telemetry/fixtures/fastlapsegment.json
  components/paddock/telemetry/fixtures/filter.sh
  components/paddock/telemetry/fixtures/lap.json
  components/paddock/telemetry/fixtures/session.json
  components/paddock/telemetry/fixtures/track.json
  components/paddock/telemetry/migrations/0010_alter_fastlap_options_car_created_car_modified_and_more.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/telemetry/tests/test_racing_stats.py
Labels: size/XXL, approved

#339 fix tests
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
Labels: size/M, approved

#342 split laps at -100 meters at the beginning of each sector
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
Labels: size/XXL, approved

#343 report coaching on delta
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/paddock/fastlap_app.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/racing_stats.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  manifests/base/paddock/ingress.yaml
Labels: size/XXL, approved

#345 tweak sector extraction
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/paddock/fastlap_app.py
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
Labels: size/XXL, approved

#346 adjust to new grafana controller and new extended dashboard
  manifests/base/grafana-v5/dashboards/details-crew-chief.yaml
  manifests/base/grafana-v5/dashboards/details-extended.yaml
  manifests/base/grafana-v5/dashboards/driver.yaml
  manifests/base/grafana-v5/dashboards/kustomization.yaml
  manifests/base/grafana-v5/datasource-influx.yaml
Labels: size/XXL, approved

#347 add psql grafana data source
  manifests/base/grafana-v5/datasource-psql.yaml
  manifests/base/grafana-v5/kustomization.yaml
  manifests/base/postgresql/pgo-reader.sealed.yaml
  manifests/base/postgresql/pgo-reader.sops.yaml
  manifests/env/phobos/postgresql/kustomization.yaml
  manifests/env/phobos/postgresql/pgo-reader.sealed.yaml
Labels: size/L, approved

#348 misc stuff
  README.md
  components/paddock/telemetry/pitcrew/session.py
  docs/backup.md
  manifests/base/telegraf/telegraf.conf
  manifests/env/phobos/kustomization.yaml
  manifests/env/phobos/telegraf/kustomization.yaml
  scripts/psql.sh
  scripts/publish.sh
  scripts/sample.json
  scripts/setup_secrets.sh
  scripts/subscribe.sh
Labels: size/M, approved

#349 adjust timing of sending responses
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
Labels: approved, size/S

#352 Update details-extended.yaml
  manifests/base/grafana-v5/dashboards/details-extended.yaml
Labels: size/XXL, approved, ok-to-test

#354 Update details-extended.yaml
  manifests/base/grafana-v5/dashboards/details-extended.yaml
Labels: size/L, approved, ok-to-test

#356 removing the -1y ranges to normal grafana ranges and setting the range default to 7 days
  manifests/base/grafana-v5/dashboards/details-extended.yaml
Labels: size/XXL, approved, ok-to-test

#357 influx config
  manifests/base/influxdb/cronjob-backup.yaml
  manifests/base/influxdb/influx-config.yaml
  manifests/base/influxdb/influx-vars.yaml
  manifests/base/influxdb/influxdb2-values.yaml
  manifests/base/influxdb/influxdb2/influxdb/templates/configmap-backup.yaml
  manifests/base/influxdb/influxdb2/influxdb/templates/cronjob-backup.yaml
  manifests/base/influxdb/influxdb2/influxdb/templates/deployment.yaml
  manifests/base/influxdb/influxdb2/influxdb/templates/pvc-backup.yaml
  manifests/base/influxdb/influxdb2/influxdb/templates/pvc.yaml
  manifests/base/influxdb/influxdb2/influxdb/templates/service.yaml
  manifests/base/influxdb/influxdb2/influxdb/templates/serviceaccount.yaml
  manifests/base/influxdb/kustomization.yaml
  manifests/env/phobos/influxdb/kustomization.yaml
  manifests/env/phobos/kustomization.yaml
Labels: size/L, approved

#358 add coaching mode
  components/paddock/paddock/views.py
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/fixtures/coach.json
  components/paddock/telemetry/migrations/0011_remove_coach_track_walk_coach_mode.py
  components/paddock/telemetry/migrations/0012_alter_coach_mode.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/message.py
  manifests/env/phobos/influxdb/kustomization.yaml
  scripts/parse_log.py
Labels: size/L, approved

#359 debuging modes
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/paddock/fastlap_app.py
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  manifests/base/grafana-v5/dashboards/driver.yaml
  scripts/parse_log.py
Labels: size/XXL, approved

#353 Update for Driver Dashboard
  manifests/base/grafana-v5/dashboards/driver.yaml
Labels: approved, size/XL, ok-to-test

#360 revert back old driver dashboard
  manifests/base/grafana-v5/dashboards/driver-extended.yaml
  manifests/base/grafana-v5/dashboards/driver.yaml
  manifests/base/grafana-v5/dashboards/kustomization.yaml
Labels: size/XXL, approved

#364 corner approach_speed
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/paddock/fastlap_app.py
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  scripts/parse_log.py
Labels: approved, size/XL
