Repository b4mad/racing, pull requests merged in 2023-06, with the labels that each got.

#293 fix psql and influx backup configmap / fix psql and influx backup configmap
  manifests/env/phobos-test/kustomization.yaml
  manifests/env/phobos-test/namespace.yaml
  manifests/env/phobos-test/paddock-ingress.yaml
  manifests/env/phobos-test/paddock-settings.yaml
  manifests/env/phobos-test/rebuild/kustomization.yaml
  manifests/env/phobos.dev/README.md
  manifests/env/phobos.dev/kustomization.yaml
  manifests/env/phobos.dev/namespace.yaml
  manifests/env/phobos.test/influx/kustomization.yaml
  manifests/env/phobos.test/kustomization.yaml
  manifests/env/phobos/influxdb/configmap-backup.yaml
  manifests/env/phobos/influxdb/kustomization.yaml
  manifests/env/phobos/kustomization.yaml
Labels: size/L

#294 remove all secrets
  manifests/base/grafana-v5/kustomization.yaml
  manifests/base/influxdb/kustomization.yaml
  manifests/base/paddock/kustomization.yaml
  manifests/base/postgresql/kustomization.yaml
  manifests/base/postgresql/pgo-s3-creds.sealed.yaml
  manifests/base/postgresql/pgo-s3-creds.sops.yaml
  manifests/base/postgresql/s3.conf
  manifests/env/phobos/influxdb/configmap-backup.yaml
  manifests/env/phobos/postgresql/kustomization.yaml
  manifests/env/phobos/postgresql/pgo-s3-creds.sealed.yaml
Labels: size/L

#289 edge case in resampling / fine tune read time
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
Labels: approved, size/S

#295 refactor segment / avg telmetry values
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
Labels: size/L, approved

#296 show telemetry in fast lap
  components/paddock/notebooks/segments.ipynb
  components/paddock/paddock/fastlap_app.py
  components/paddock/paddock/templates/fastlap_dash.html
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/influx.py
  components/paddock/telemetry/visualizer.py
Labels: size/XXL, approved

#297 bump paddock memory
  manifests/base/paddock/ingress.yaml
  manifests/env/phobos/kustomization.yaml
Labels: size/S

#298 bump plotly-dash
  components/paddock/Pipfile.lock
Labels: size/L, approved

#299 ✨ add telemetry e2e test
  .prow.yaml
  .tekton/push.yaml
  .tekton/tasks/e2e-telemetry-test.yaml
  components/paddock/README.md
  components/paddock/e2e-test.sh
  components/paddock/paddock/settings.py
Labels: size/L

#302 rework fast lap UI
  components/paddock/paddock/fastlap_app.py
  components/paddock/paddock/templates/fastlap.html
  components/paddock/paddock/templates/fastlap_dash.html
  components/paddock/paddock/templates/fastlap_index.html
  components/paddock/paddock/templates/home.html
  components/paddock/paddock/urls.py
  components/paddock/paddock/views.py
  components/paddock/telemetry/racing_stats.py
Labels: size/L, approved

#304 tests
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/racing_stats.py
  components/paddock/telemetry/tests/data/responses_fastlap_analyzer_37672.txt
  components/paddock/telemetry/tests/data/responses_fastlap_analyzer_40781.txt
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/telemetry/tests/test_fast_lap_analyzer.py
  components/paddock/telemetry/tests/test_history.py
  components/paddock/telemetry/tests/test_racing_stats.py
  components/paddock/telemetry/tests/utils.py
Labels: size/XXL, approved

#303 📝 describe how to use sops-encrypted file to recreate sealed secrets
  manifests/README.md
Labels: approved, size/S

#305 segments
  components/paddock/paddock/fastlap_app.py
  components/paddock/scripts/dumpdata.sh
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/fixtures/coach.json
  components/paddock/telemetry/fixtures/fastlap.json
  components/paddock/telemetry/fixtures/fastlapsegment.json
  components/paddock/telemetry/fixtures/filter.sh
  components/paddock/telemetry/fixtures/lap.json
  components/paddock/telemetry/fixtures/session.json
  components/paddock/telemetry/fixtures/track.json
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/logging.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_fastlap_analyzer_37672.txt
  components/paddock/telemetry/tests/data/responses_fastlap_analyzer_40781.txt
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  components/paddock/telemetry/tests/test_fast_lap_analyzer.py
  components/paddock/telemetry/tests/test_racing_stats.py
Labels: size/XXL, approved

#309 fix migrate
  components/paddock/paddock/fastlap_app.py
Labels: size/XS

#310 new track guide approach
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/notebooks/segments.ipynb
  components/paddock/telemetry/influx.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/racing_stats.py
Labels: size/L, approved

#306 ✨ 🌡️ add prometheus metrics exporter basics
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/paddock/settings.py
  components/paddock/paddock/urls.py
  components/paddock/telemetry/models.py
  manifests/base/paddock/deployment_config.yaml
  manifests/base/paddock/kustomization.yaml
  manifests/base/paddock/paddock-settings.yaml
Labels: size/L, approved

#314 update pre commit
  .pre-commit-config.yaml
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/notebooks/django_initializer.py
  components/paddock/paddock/fastlap_app.py
  components/paddock/paddock/pitcrew_app.py
  components/paddock/paddock/settings.py
  components/paddock/paddock/views.py
  components/paddock/pyproject.toml
  components/paddock/telemetry/admin.py
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/fast_lap_analyzer_v1.py
  components/paddock/telemetry/fast_lap_analyzer_v2.py
  components/paddock/telemetry/fast_lap_analyzer_v3.py
  components/paddock/telemetry/influx.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/management/commands/load_devel_data.py
  components/paddock/telemetry/management/commands/maintenance.py
  components/paddock/telemetry/management/commands/pitcrew.py
  components/paddock/telemetry/management/commands/replay.py
  components/paddock/telemetry/management/commands/replay_to_db.py
  components/paddock/telemetry/migrations/0001_initial.py
  components/paddock/telemetry/migrations/0002_auto_20221201_1729.py
  components/paddock/telemetry/migrations/0003_auto_20221203_2100.py
  components/paddock/telemetry/migrations/0004_lap_end.py
  components/paddock/telemetry/migrations/0005_fastlap_data.py
  components/paddock/telemetry/migrations/0006_alter_car_options_alter_driver_options_and_more.py
  components/paddock/telemetry/migrations/0007_remove_fastlap_lap_lap_fast_lap.py
  components/paddock/telemetry/migrations/0009_coach_fast_lap_coach_track_walk.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/coach_watcher.py
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/firehose.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/mqtt.py
  components/paddock/telemetry/pitcrew/session.py
  components/paddock/telemetry/pitcrew/session_saver.py
  components/paddock/telemetry/racing_stats.py
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/telemetry/tests/test_fast_lap_analyzer.py
  components/paddock/telemetry/tests/test_history.py
  components/paddock/telemetry/tests/test_racing_stats.py
  components/paddock/telemetry/tests/test_session.py
  components/paddock/telemetry/tests/utils.py
  flux/tasks/brake_start.py
  flux/tasks/gears.py
  notebooks/analysis/src/compare.py
  notebooks/analysis/src/preprocess.py
Labels: approved, size/XL

#315 🖹 update the readme: how to use a local postgresql
  components/paddock/README.md
  components/paddock/paddock/settings.py
Labels: approved, size/XS

#311 show track guid message on fastlapp_app
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/notebooks/segments.ipynb
  components/paddock/paddock/fastlap_app.py
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/visualizer.py
Labels: size/XXL, approved

#316 add db settings to analyze cronjob
  manifests/base/paddock/cronjob_analyze.yaml
  manifests/base/paddock/cronjobs/cronjob_analyze.yaml
Labels: approved

#317 remove global var
  components/paddock/paddock/fastlap_app.py
Labels: approved, size/S

#320 improve coach startup
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  components/paddock/telemetry/tests/test_coach.py
Labels: size/L, approved

#321 fetch telemetry from multiple laps -> optimal lap
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/notebooks/segments.ipynb
  components/paddock/paddock/fastlap_app.py
  components/paddock/paddock/templates/coach.html
  components/paddock/paddock/views.py
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/influx.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/segment.py
  components/paddock/telemetry/tests/data/responses_test_coach.txt
  components/paddock/telemetry/tests/test_fast_lap_analyzer.py
Labels: size/XXL, approved

#323 only save fast_lap on change
  components/paddock/telemetry/management/commands/analyze.py
Labels: approved, size/S

#327 smarter sector extraction
  components/paddock/notebooks/fast_laps.ipynb
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/visualizer.py
Labels: size/XXL, approved
