Repository b4mad/racing, pull requests merged in 2023-05, with the labels that each got.

#229 get mqtt host from env
  components/paddock/telemetry/pitcrew/coach_watcher.py
  components/paddock/telemetry/pitcrew/crew.py
  components/paddock/telemetry/pitcrew/mqtt.py
  components/paddock/telemetry/pitcrew/session_saver.py
  manifests/base/paddock/paddock-settings.yaml
Labels: size/S

#230 mqtt ready logic
  components/paddock/telemetry/pitcrew/mqtt.py
Labels: size/XS

#231 session_saver integrity check
  components/paddock/telemetry/pitcrew/session_saver.py
  components/paddock/telemetry/tests.py
Labels: size/M

#232 replay mqtt
  components/paddock/telemetry/management/commands/replay.py
Labels: size/S

#233 replay mqtt better influx connection handling
  components/paddock/telemetry/influx.py
  components/paddock/telemetry/management/commands/replay.py
Labels: size/S

#241 refactor: Refactor fast lap display for better readability and usability
  components/paddock/paddock/templates/fastlap_index.html
  components/paddock/paddock/views.py
Labels: size/S

#242 analyzer test
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/fixtures/car.json
  components/paddock/telemetry/fixtures/coach.json
  components/paddock/telemetry/fixtures/driver.json
  components/paddock/telemetry/fixtures/fastlap.json
  components/paddock/telemetry/fixtures/fastlapsegment.json
  components/paddock/telemetry/fixtures/filter.sh
  components/paddock/telemetry/fixtures/lap.json
  components/paddock/telemetry/fixtures/session.json
  components/paddock/telemetry/fixtures/sessiontype.json
  components/paddock/telemetry/fixtures/track.json
  components/paddock/telemetry/influx.py
  components/paddock/telemetry/tests/data/lap_37672_df.csv.gz
  components/paddock/telemetry/tests/data/lap_40781_df.csv.gz
  components/paddock/telemetry/tests/data/session_1672395579_df.csv.gz
  components/paddock/telemetry/tests/data/session_1673613558_df.csv.gz
  components/paddock/telemetry/tests/data/session_1673613558_valid_markers.png
  components/paddock/telemetry/tests/data/session_1680321341_df.csv.gz
  components/paddock/telemetry/tests/data/session_1681021274_df.csv.gz
  components/paddock/telemetry/tests/data/session_1681021274_valid_markers.png
  components/paddock/telemetry/tests/data/session_1681897871_df.csv.gz
  components/paddock/telemetry/tests/data/session_1682107191_df.csv.gz
  components/paddock/telemetry/tests/data/session_1683388042_df.csv.gz
  components/paddock/telemetry/tests/test_fast_lap_analyzer.py
  components/paddock/telemetry/tests/utils.py
Labels: size/XL

#243 fast_laps store the laps from which they've been created
  components/paddock/paddock/urls.py
  components/paddock/stewards/__init__.py
  components/paddock/stewards/admin.py
  components/paddock/stewards/apps.py
  components/paddock/stewards/migrations/__init__.py
  components/paddock/stewards/models.py
  components/paddock/stewards/tests.py
  components/paddock/stewards/urls.py
  components/paddock/stewards/views.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/management/commands/analyze.py
  components/paddock/telemetry/migrations/0006_alter_car_options_alter_driver_options_and_more.py
  components/paddock/telemetry/migrations/0007_remove_fastlap_lap_lap_fast_lap.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/tests/test_coach.py
Labels: size/L

#247 rewrite lap segmentation and fast lap analysis :metal:
  .pre-commit-config.yaml
  components/paddock/Pipfile
  components/paddock/Pipfile.lock
  components/paddock/notebooks/lap.ipynb
  components/paddock/notebooks/segments.ipynb
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/fast_lap_analyzer_v3.py
  components/paddock/telemetry/management/commands/analyze.py
Labels: size/XXL

#248 edge case: lap with full throttle
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/management/commands/analyze.py
  manifests/base/postgresql/cluster.yaml
Labels: size/M

#249 refactor coach
  components/paddock/notebooks/segments.ipynb
  components/paddock/scripts/dumpdata.sh
  components/paddock/telemetry/fixtures/fastlap.json
  components/paddock/telemetry/fixtures/fastlapsegment.json
  components/paddock/telemetry/fixtures/lap.json
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/tests/test_coach.py
Labels: size/XL

#250 refactoring coaching and history
  components/paddock/notebooks/segments.ipynb
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/tests/test_coach.py
Labels: size/XXL

#251 dynamic brake message
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/tests/test_coach.py
Labels: size/XL

#253 add status to coach
  components/paddock/paddock/pitcrew_app.py
  components/paddock/telemetry/fixtures/fastlap.json
  components/paddock/telemetry/fixtures/fastlapsegment.json
  components/paddock/telemetry/fixtures/filter.sh
  components/paddock/telemetry/migrations/0008_coach_status_alter_coach_error.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/telemetry/tests/test_fast_lap_analyzer.py
Labels: size/XL

#257 send msg 100 meters earlier instead of 10
  components/paddock/paddock/templates/account/base.html
  components/paddock/paddock/templates/account/login.html
  components/paddock/paddock/views.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/message.py
Labels: size/M

#259 always log a session_id
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/firehose.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/logging.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/session.py
Labels: size/L

#262 better debugging messages
  components/paddock/README.md
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
Labels: size/S

#261 Tls-redirect
  manifests/base/keycloak/base/route.yaml
  manifests/base/paddock/route.yaml
  manifests/env/phobos/paddock-ingress.yaml
  manifests/env/smaug/grafana/route.yaml
  manifests/env/smaug/influxdb/routes.yaml
Labels: size/M, lgtm, approved, ok-to-test

#263 ingress follow up
  manifests/base/paddock/kustomization.yaml
  manifests/base/paddock/paddock-ingress.yaml
  manifests/env/phobos/kustomization.yaml
Labels: approved, size/S

#271 add ingress to grafana
  manifests/base/grafana-v5/grafana.yaml
  manifests/base/grafana-v5/ingress.yaml
  manifests/base/grafana-v5/kustomization.yaml
  manifests/env/phobos.test/kustomization.yaml
  manifests/env/phobos/kustomization.yaml
Labels: size/L, lgtm

#276 new coach
  components/paddock/paddock/templates/coach.html
  components/paddock/paddock/views.py
  components/paddock/telemetry/migrations/0009_coach_fast_lap_coach_track_walk.py
  components/paddock/telemetry/models.py
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/pitcrew/mqtt.py
  components/paddock/telemetry/tests/test_coach.py
Labels: size/XXL

#278 fix driving backwards / adjust time to read
  components/paddock/telemetry/pitcrew/coach.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
Labels: size/M, approved

#279 s3 backup for pgo
  manifests/base/postgresql/README.md
  manifests/base/postgresql/cluster.yaml
  manifests/base/postgresql/kustomization.yaml
  manifests/base/postgresql/s3.conf
  manifests/env/phobos.test/kustomization.yaml
  manifests/env/phobos.test/postgresql/kustomization.yaml
  manifests/env/phobos/postgresql/kustomization.yaml
Labels: size/L

#281 fine tune segment lengths and messages
  components/paddock/notebooks/segments.ipynb
  components/paddock/telemetry/analyzer.py
  components/paddock/telemetry/fast_lap_analyzer.py
  components/paddock/telemetry/pitcrew/history.py
  components/paddock/telemetry/pitcrew/message.py
  components/paddock/telemetry/tests/test_coach.py
  components/paddock/telemetry/tests/test_fast_lap_analyzer.py
Labels: approved, size/XL

#283 if CurrentLapTime is not monotonic, use linspace
  components/paddock/notebooks/segments.ipynb
  components/paddock/telemetry/analyzer.py
Labels: size/L

#285 recursion fix duh
  components/paddock/telemetry/analyzer.py
Labels: size/XS

#286 edge case: only one sector
  components/paddock/telemetry/analyzer.py
Labels: approved, size/XS
